### ISSUE TITLE
Add debug logs to show where docker/distribution credentials came from

### ISSUE THREAD

**Issue by mtrmac** [containers/image#510] opened 2018-10-01 17:19 UTC
- Were they provided in `types.SystemContext`?
- Were they read from a config file? If so, from which one?
- Are we using no credentials at all?

**Comment by rhatdan** [comment] 2019-04-25 09:45
@mtrmac @vrothberg What is the state of this issue?  Do you want me to get someone else to work on it?

**Comment by vrothberg** [comment] 2019-04-25 11:23
The issue is still valid and I absolutely agree that such logs are needed.

Marked as `Good first issue` which may be something for interns or new contributors :)

**Closed** 2019-06-24 10:54 UTC
Labels: Good first issue
