### ISSUE TITLE
Implement mirror support for docker-client

### ISSUE THREAD

**Issue by saschagrunert** [containers/image#559] opened 2019-01-15 15:42 UTC
Hey, I would like to work on the topic of implementing the full mirror support for the internal docker client (`docker/docker_client.go`). My main approach would be to hook into the client and try the parsed mirrors directly there. Beside that #529 mentioned missing documentation, which could be added as well if the main design should not change.

@vrothberg what do you think about this? Are there already other planned changes related to that?

**Comment by vrothberg** [comment] 2019-01-15 16:12
Hi @saschagrunert, thanks for the request and offering help!

Before implementing the mirror support, we need to decide if we want to keep the current design of `sysregistriesv2` or if we switch to the push/pull endpoints semantics as the elephant-baby-PR over at Moby does.

As none of the main tools (Podman, CRI-O etc.) are using the new `registries.conf` format, we still have the chance to change it. I am tempted to follow the current design of the Moby PR but unless it's merged, there is no guarantee it won't change again.

@mtrmac WDYT? We were chatting about that already but I lost track of it and believe that there is no decision yet.

Once we know where to go, we can figure out the details.

**Comment by mtrmac** [comment] 2019-01-15 18:46
> As none of the main tools (Podman, CRI-O etc.) are using the new registries.conf format, we still have the chance to change it. I am tempted to follow the current design of the Moby PR but unless it's merged, there is no guarantee it won't change again.
>
> @mtrmac WDYT? We were chatting about that already but I lost track of it and believe that there is no decision yet.

**Comment by mtrmac** [comment] 2019-01-15 18:57
(re: the above; note that the discussion about the `sysregistriesv2` data structures and syntax is fairly orthogonal to the c/image/docker implementation; whatever the data structures end up being, adapting the c/image/docker client should be ~trivial.)

I think the earlier discussion is around 
https://github.com/containers/image/pull/468#issuecomment-440254302 and following.

A quick summary of my current impressions of that:

I’m still not truly convinced about ever exposing the `/v2` API path, and the precise `registry-1.docker.io` host name, to users. It very much looks like something that they should not need to care about, and multiple servers on the same host seem to me like a very obscure corner case in the current fashion of single server per {VM,container} (though I could well be wrong about this one).

Having “just” an array of `pull` entries, instead of a primary URL vs. structurally-different `Mirrors`, is nicely symmetrical, OTOH it requires extra syntax==noise in the no-mirror case, so it’s not _clearly_ worthwhile.

Dealing with TLS configuration for mirrors is another question to be decided — should it be per (prefix+mirror), which means duplicating the TLS options for every prefix if a mirror registry mirrors multiple upstreams, or should it be a separate top-level entry, which means the TLS options are set once, but a simple single-purpose mirror now means configuration in two places?

---

On yet another hand, having the same configuration structure, and ideally the same syntax, as Docker, would be very attractive, even if it required some design compromises — but it would be that attractive if there were a clear path to both project actually implementing that same syntax; a PR in limbo is much weaker.

**Comment by saschagrunert** [comment] 2019-01-16 11:10
Thanks for the comprehensive information! It would be really cool if we can keep track of the final design somewhere. My idea would be to start with the documentation part in [docs/containers-registries.conf.5.md](https://github.com/containers/image/blob/b16716c/docs/containers-registries.conf.5.md) and implement it afterwards in a follow up PR. WDYT?

I have multiple thoughts related to the current design, too. I will drop them here and feel free to shut me down if the topic already has been discussed for quite a while:

- I think we would need some configuration validation and result caching with my proposals below.
- A possible live reload of the configuration would be awesome.
- Finding out supported schemes (http/s) could be done automatically
- The `InsecureSkipVerify` flag should be set per registry endpoint and not globally
- I would rename the `Prefix` to something like `Alias` and allow multiple (non-)urls there (like `local` as alias for `my-local-registry.com`). This would incorporate changes in the qualified vs unqualified image pull behavior in cri-o.
- We should have some default built-in registries for unqualified push/pull, like `docker` and `quay`, which are already pre-configured so that the user just has to enable/disable them
- The v2/v1 handling via the URL path should be done out of scope of the user configuration and could be done automatically
- It should be possible to allow sub-paths in URLs, like `quay.io/foo/bar` could be a registry with an alias to `quay`.
- It should be possible to store the credentials needed for authenticating against a registry in a supported keyring/keychain.
- I would also use the `Endpoint` structure from the moby PR, too:
https://github.com/moby/moby/blob/8175dcf169ffebf84f85a2c17d4f7152aaf78100/api/types/registry/registry.go#L53-L65
but would make the usage in the TOML file a bit more flexible.

So this would be my final proposal:

```toml
[registries]
# The overall priority of the registries for unqualified push/pull can be
# defined via their identifiers from high to low:
unqualified-priority = [
    "docker",
    "quay",
    "google",
    "registry2",
]

# This section contains pre-defined registries, which can be enabled/disabled
# for unqualified pull/push. It is possible to alias them too, but the
# identifiers (like `docker`) are reserved and cannot be used somewhere else.
[default]
docker = true     # will internally use https://registry-1.docker.io
docker-cn = false # would use https://registry.docker-cn.com, but is disabled
quay = true

# A pull/push to gg/google-containers/hyperkube:v1.13.2
# will result in gcr.io/google-containers/hyperkube:v1.13.2
google = { enabled = true, alias = "gg" }

[custom]
# This registry container multiple aliases and will use http as scheme
# A pull/push to reg0/image
# will result in my-reg0.local/path/image:latest
registry0 = { url = "http://my-reg0.local/path", aliases = ["reg0", "reg", "r"] }

# This registry will use TLS but skip the certificate validation
# Direct push/pull is possible via `my-reg1.local` or the alias `reg1`
registry1 = { url = "https://my-reg1.local", skipTLSVerify = true, aliases = ["reg1"] }

# This registry contains `registry0` and `registry1` as mirrors. There is no
# need to specify an `url` if we have an alias and mirrors. That's also why
# `registry0` and `registry1` are not part of the `priority` list above.
registry2 = { aliases = ["reg2"], mirrors = ["registry0", "registry1"] }

# It is possible to specify mirrors of default registries as well. So a
# push/pull to my-reg3.local/image will first try the official docker registry.
registry3 = { url = "my-reg3.local", mirrors = ["docker"] }

# The simpliest specification of a registry is just a domain, if possible, it
# will resolve to: `https://reg4.com/` or `http://reg4.com/`
registry4 = "reg4.com"
```

Bear with me and the high impact of the proposal as well as the alien syntax. :) What do you think? @vrothberg @mtrmac

**Comment by mtrmac** [comment] 2019-01-16 11:54
Thanks for all the ideas.

Just a few quick thoughts for now — initial personal impressions, _not_ authoritative; others may well have different opinions.

> * I think we would need some configuration validation and result caching with my proposals below.

This already mostly exists, doesn’t it?

> * Finding out supported schemes (http/s) could be done automatically

The “is non-TLS connection allowed” decision can _not_ be autodetected; an attacker could just prevent TLS connections to force downgrade to non-TLS which can then be attacked. (c/image/docker already autodetects TLS/non-TLS if non-TLS is allowed).

> * The `InsecureSkipVerify` flag should be set per registry endpoint and not globally

Isn’t that already the case? Or maybe, which flag are you talking about? The one in `SystemContext` is not explicitly scoped, but the caller can set a different value for each call.

> * I would rename the `Prefix` to something like `Alias` and allow multiple (non-)urls there (like `local` as alias for `my-local-registry.com`).

This wouldn’t easily work this way because docker/distribution/reference==c/image/docker/reference normalizes `local/foo` to `docker.io/local/foo` at the point of parsing the strings into a `reference.Named` (i.e., in an ideal application caller, at the top level [like a CLI flag parser] that decides what to pull, way before c/image is involved, and also before the configuration `sysregistriesv2` is ever applied to the value).

Also, personally I’m quite opposed to introducing yet another string syntax that _looks_ the same but means something quite different, and the user is supposed to know which syntax applies where. At least some of this would be resolved by using a different character forbidden in docker/distribution references (e.g. `$local`), but that would still change the semantics of references throughout the API, and make them meaningless without access to the corresponding `sysregistriesv2` configuration.

At a higher level, this is a very CLI- and manual-operation-focused feature (or…I hope? Or is the suggestion that Kubernetes image specs would also process these aliases?); it’s not obvious to me that it easily generalizes to other uses (“how would one build a GUI for this?”), and the complexity of the configuration (_two_ different places to define an alias? being ~essentially forced to define an alias in order to set the search order? many aliases pointing to exactly the same registry?) seems way too high, when the kinds of users I can imagine can get quite similar results with shell aliases or shell functions. [I could well be wrong about this.]

> This would incorporate changes in the qualified vs unqualified image pull behavior in cri-o.

FWIW c/image/docker very intentionally does not implement the unqualified image search mechanism the way podman does right now; basically it breaks signatures and it’s not at all clear how it can not break them, because the user intent about which image to pull is ambiguous.

> * We should have some default built-in registries for unqualified push/pull, like `docker` and `quay`, which are already pre-configured so that the user just has to enable/disable them

See above, single-word prefixes have an entirely different meaning already.

> * The v2/v1 handling via the URL path should be done out of scope of the user configuration and could be done automatically

We don’t implement v1 at all (except for search), and have no serious intention to, FWIW.

> * It should be possible to store the credentials needed for authenticating against a registry in a supported keyring/keychain.

This is quite orthogonal to `sysregistriesv2` AFAICS. `c/image/pkg/docker/config` does support credential helpers.

**Comment by saschagrunert** [comment] 2019-01-16 14:51
Thank you very much for the fast response!

> > * I think we would need some configuration validation and result caching with my proposals below.
> 
> This already mostly exists, doesn’t it?

I know that cri-o has some configuration validation but I am not sure how much this topic belongs into c/images. What I wanted to say is if we go in some direction of having more flexibility in the registries configuration, it would be good to have an configuration validation for `sysregistriesv2` (during startup or change of the file) to avoid logical issues. One trivial example would be defining a registry twice with different configuration parameters. An approach could be to add an configuration validation to `sysregistriesv2` and execute it from cri-o directly on startup.

> > * Finding out supported schemes (http/s) could be done automatically
> 
> The “is non-TLS connection allowed” decision can _not_ be autodetected; an attacker could just prevent TLS connections to force downgrade to non-TLS which can then be attacked. (c/image/docker already autodetects TLS/non-TLS if non-TLS is allowed).

Okay, I think you are referring to that ping test in `detectPropertiesHelper()`:
https://github.com/containers/image/blob/3dda079ae672eb11d7b62e6f85a3283c5b560153/docker/docker_client.go#L582-L585

I guess it's fine to keep the current implementation approach. We just need a way to tell the user that it is wrong to specify the scheme in an endpoint as early as possible (not just on image pull/push), right?

> 
> > * The `InsecureSkipVerify` flag should be set per registry endpoint and not globally
> 
> Isn’t that already the case? Or maybe, which flag are you talking about? The one in `SystemContext` is not explicitly scoped, but the caller can set a different value for each call.

Yep you're right, I got that wrong. It is scoped to the docker client and will be set on `newDockerClient`.

> > * I would rename the `Prefix` to something like `Alias` and allow multiple (non-)urls there (like `local` as alias for `my-local-registry.com`).
> 
> This wouldn’t easily work this way because docker/distribution/reference==c/image/docker/reference normalizes `local/foo` to `docker.io/local/foo` at the point of parsing the strings into a `reference.Named` (i.e., in an ideal application caller, at the top level [like a CLI flag parser] that decides what to pull, way before c/image is involved, and also before the configuration `sysregistriesv2` is ever applied to the value).
> 
> [...]

Yeah I get your point. :+1: I mean it was more or less a crazy idea and keeping the prefix behavior like in the current implementation would be fine too. We could consider allowing multiple prefixes, but I'm not sure if there is a real world use case for that.

> > This would incorporate changes in the qualified vs unqualified image pull behavior in cri-o.
> 
> FWIW c/image/docker very intentionally does not implement the unqualified image search mechanism the way podman does right now; basically it breaks signatures and it’s not at all clear how it can not break them, because the user intent about which image to pull is ambiguous.
> 
> > * We should have some default built-in registries for unqualified push/pull, like `docker` and `quay`, which are already pre-configured so that the user just has to enable/disable them
> 
> See above, single-word prefixes have an entirely different meaning already.
> 
> > * The v2/v1 handling via the URL path should be done out of scope of the user configuration and could be done automatically
> 
> We don’t implement v1 at all (except for search), and have no serious intention to, FWIW.

Okay, should be fine if this is the intended behavior. :)

> > * It should be possible to store the credentials needed for authenticating against a registry in a supported keyring/keychain.
> 
> This is quite orthogonal to `sysregistriesv2` AFAICS. `c/image/pkg/docker/config` does support credential helpers.

Yeah nice, than this actually works pretty intentional.

**Comment by vrothberg** [comment] 2019-01-16 15:02
> Thank you very much for the fast response!
> 
> > > * I think we would need some configuration validation and result caching with my proposals below.
> > 
> > 
> > This already mostly exists, doesn’t it?
> 
> I know that cri-o has some configuration validation but I am not sure how much this topic belongs into c/images. What I wanted to say is if we go in some direction of having more flexibility in the registries configuration, it would be good to have an configuration validation for `sysregistriesv2` (during startup or change of the file) to avoid logical issues. One trivial example would be defining a registry twice with different configuration parameters. An approach could be to add an configuration validation to `sysregistriesv2` and execute it from cri-o directly on startup.

Some validation happens in `sysregistriesv2` already see `postProcessRegistries()`. There is no duplicate check yet, though :)

**Comment by vrothberg** [comment] 2019-01-16 16:27
> [...]
> Some validation happens in `sysregistriesv2` already see `postProcessRegistries()`. There is no duplicate check yet, though :)

Actually, it does duplicate checks.

**Comment by saschagrunert** [comment] 2019-01-17 08:21
@vrothberg @mtrmac Thanks for making the picture clearer to me. :+1: What I discerned so far is that an implementation close to https://github.com/moby/moby/pull/34319 is suggestive. Since I am not aware of how your decision process works, I would like to ask you what the next steps are?

**Comment by vrothberg** [comment] 2019-01-17 09:45
Quoting @mtrmac:

> (re: the above; note that the discussion about the sysregistriesv2 data structures and syntax is fairly orthogonal to the c/image/docker implementation; whatever the data structures end up being, adapting the c/image/docker client should be ~trivial.)

This sounds fair. In case the data structures will change in the future, adapting to it should be straight forward once mirror-support is implemented in the `dockerClient`, which has very similar requirements as the Moby PR:

- **Select a matching registry** via `sysregistryv2.FindRegistry(...)`. If none is found, follow the common code path.
- Independent if we use a mirror or not, we need to **rewrite the reference** based on the prefix (strip and prepend). There is no API for this yet in `sysregistriesv2` but the code can be more or less copied from the elephant-baby-PR over at Moby and added into something like `Registry.RewriteReference(...)`.
- **Iterate through the slice of "endpoints"** via `append(registry.Mirrors, regisry.URL)` and try pulling from them.
  - Here we need to be extra careful regarding authentication. If credentials are set via the `SystemContext`, we should ignore mirrors since the (user-specified) credentials relate to the intial reference we want to pull.

I am not yet 100 percent sure how the notion of mirrors should be integrated. **Where should we iterate over the mirrors?**

We abstract pulling/copying images in `copy.Image` as containers/image supports various kinds of transports. Copying the different parts of an image (manifest, individual blobs/layers) includes several different operations which are invoked in/triggered by `copy.Image`. If we pull layer-N but pulling layer-N+1 fails, should we try the next mirror? I think *yes* and in this case, we need to move the semantics up into `copy.Image` and may extend  `types.ImageSource` with an interface that allows to re-try copying. To me, this sounds the most straight-forward way but I may be wrong and I definitely trust @mtrmac 's competences.

**Comment by mtrmac** [comment] 2019-01-17 19:09
> > (re: the above; note that the discussion about the sysregistriesv2 data structures and syntax is fairly orthogonal to the c/image/docker implementation; whatever the data structures end up being, adapting the c/image/docker client should be ~trivial.)
> 
> This sounds fair. In case the data structures will change in the future, adapting to it should be straight forward once mirror-support is implemented in the `dockerClient`,

Note that the “orthogonal” comment is mostly about the _relative_ timing of the mirroring implementation and configuration design; ideally, we should _release_ both of these at about the same time, so that there is never an user-breaking configuration format change.

(Or, well, we could continue to support the older format indefinitely in the code. Maybe that’s the easiest way to move forward? Keeping around a bit of code with tests seems quite cheap, compared to weeks of trying to abstractly invent a “perfect” design.)

@saschagrunert Looking at the `[custom]` section of the proposal in 
https://github.com/containers/image/issues/559#issuecomment-454741683 , and discounting the alias mechanism [Is that reasonable? Or is the alias idea something important that we should try hard to get into the design in the first iteration?], the configuration seems pretty similar to the current `Prefix`/`URL`/`Mirrors` data structure. Is that because that’s the structure that most fits your uses, or because the existing data structures were used as a starting point and you don’t have a preference in this aspect?

@vrothberg WRT the Moby design, what does the array of `Push` endpoints actually mean?
- That each image _must_ be pushed to _all of them_?
- That an image must be pushed to any one of them, but all parts of the image to the same endpoint?
- That all the endpoints are just ~redundant URLs for the same underlying storage and it’s fine to push different blobs from a single image to different endpoints?

**Comment by mtrmac** [comment] 2019-01-17 19:09
>   * Here we need to be extra careful regarding authentication. If credentials are set via the `SystemContext`, we should ignore mirrors since the (user-specified) credentials relate to the intial reference we want to pull.

This is an important point, I didn’t realize that this needs special-casing. (I assume authenticated mirrors would need some other mechanism. Shall we defer that?)

**Comment by mtrmac** [comment] 2019-01-17 19:11
> I am not yet 100 percent sure how the notion of mirrors should be integrated. **Where should we iterate over the mirrors?**
> 
> We abstract pulling/copying images in `copy.Image` as containers/image supports various kinds of transports.

That’s not quite trivial because the concept of a mirror — or really the concept of a _remote server_ — is transport-specific; all of `sysregistriesv2` is specific to the `c/image/docker` transport, and has absolutely no connection to e.g. `dir:`.

It would be _possible_ but it looks kind of pointless for `copy.Image` to call something like `Transport.Get{Source,Destination}Mirrors`+`ImageReference.CombineWithMirror`, when the transport can just as well do this internally.

Also, the current design is that an `ImageSource`/`ImageDestination` is _stateful_ (consider e.g. the “tarball archive” transports that can create a temporary file / directory subtree when initializing the source/destination and delete it in `Close`; or how `storageImageDestination` requires all of `PutBlob`+`PutManifest` to happen; even `dockerClient` has a bit of state), and it’s not trivially obvious how mirror support applies to the very stateful cases (e.g. in the worst case when three mirrors are involved, one for a manifest and some blobs, one for a few more blobs, and one for some blobs and some signatures; does each new mirror need to be told about the operations done on the other mirror?).

OTOH, it _would_ be very nice for the `copy.Image` progress reporting to be able to say something about trying another mirror, or perhaps even (in some indeterminate future) for the parallel blob copy code to understand the existence of mirrors and to load-balance the blob copies across all available mirrors. So, maybe the locally-pointless handling of mirrors in `copy.Image` instead of inside the transport could be useful, after all?

I don’t know.

Maybe we could start with a transport-internal mechanism, because that’s going to be much easier to design, and to move to a generic implementation in `copy.Image` only as other transports implement something similar and the requirements are better understood.

Or we can just leave this up to the person writing the code :)

> Copying the different parts of an image (manifest, individual blobs/layers) includes several different operations which are invoked in/triggered by `copy.Image`. If we pull layer-N but pulling layer-N+1 fails, should we try the next mirror? I think _yes_ and in this case, we need to move the semantics up into `copy.Image`

I can’t see how switching to a different mirror on a clear error (e.g. blob missing on the first mirror) requires moving the mirror logic into the generic code. As for errors _during_ transfers…

> and may extend `types.ImageSource` with an interface that allows to re-try copying.

(BTW retries seem to me fairly orthogonal to mirroring. Yes, it may be something that we need to support — but if the generic code learns to retry e.g. blob copies, the individual transport can switch to a next mirror without much support from `copy.Image`.

OTOH e.g. Kubernetes already implements retries with backoff, and independent layers trying to retry the same operation may result in quite unexpected long delays.)

**Comment by vrothberg** [comment] 2019-01-18 11:49
> [...]
> (Or, well, we could continue to support the older format indefinitely in the code. Maybe that’s the easiest way to move forward? Keeping around a bit of code with tests seems quite cheap, compared to weeks of trying to abstractly invent a “perfect” design.)

Absolutely! I am happy we added the backwards compatibility. 

> @vrothberg WRT the Moby design, what does the array of `Push` endpoints actually mean?
> 
> * That each image _must_ be pushed to _all of them_?

Just to the first endpoint. Broadcasting might be considered in the future.

> * That an image must be pushed to any one of them, but all parts of the image to the same endpoint?

All parts must be pushed to the first endpoint.

> * That all the endpoints are just ~redundant URLs for the same underlying storage and it’s fine to push different blobs from a single image to different endpoints?

No, everything must be pushed to the first endpoint. It's really just some redirecting of the push.

But note that the elephant-baby-PR is not yet merged and the latest response from the maintainers made me wonder again if it wouldn't change yet another time.

**Comment by vrothberg** [comment] 2019-01-18 12:00
> I can’t see how switching to a different mirror on a clear error (e.g. blob missing on the first mirror) requires moving the mirror logic into the generic code. As for errors _during_ transfers…

Perfect. I looked at the code yesterday and wasn't sure if retries work *within* dockerClient which drove me to the idea of moving the logic into `copy.Image ff`.

> > and may extend `types.ImageSource` with an interface that allows to re-try copying.
> 
> (BTW retries seem to me fairly orthogonal to mirroring. Yes, it may be something that we need to support — but if the generic code learns to retry e.g. blob copies, the individual transport can switch to a next mirror without much support from `copy.Image`.

That sounds nicer *and* faster. Your mentions about progress bars made it also pretty clear to me that it's way easier to integrate the retries into dockerClient. I wouldn't want to see N times the same progress bar just because we're iterating over N mirrors.

**Comment by vrothberg** [comment] 2019-01-18 12:04
> > * Here we need to be extra careful regarding authentication. If credentials are set via the `SystemContext`, we should ignore mirrors since the (user-specified) credentials relate to the intial reference we want to pull.
> 
> This is an important point, I didn’t realize that this needs special-casing. (I assume authenticated mirrors would need some other mechanism. Shall we defer that?)

Yes, deferring sounds good to me but it definitely needs documentation. On a more positive note: we are in a less complicated situation than Moby where all credentials are stored on the *client side*. We could just look into the stored credentials - if we wish to.

**Comment by saschagrunert** [comment] 2019-01-18 12:58
> Looking at the `[custom]` section of the proposal in [#559 (comment)](https://github.com/containers/image/issues/559#issuecomment-454741683) , and discounting the alias mechanism [Is that reasonable? Or is the alias idea something important that we should try hard to get into the design in the first iteration?]

No, lets stick to the current `Prefix` notation. 

> the configuration seems pretty similar to the current `Prefix`/`URL`/`Mirrors` data structure. Is that because that’s the structure that most fits your uses, or because the existing data structures were used as a starting point and you don’t have a preference in this aspect?

My main starting point was the current structure and I experimented around with it to make it clearer to the end-user how it should be configured.

@vrothberg @mtrmac What do you think about the named endpoints and then referencing them? So for example this:

```toml
[endpoints]
endpoint1 = "my-reg1.local"
endpoint2 = "my-reg2.local"

[[registries]]
prefix = "registry.local"
pull = [ "endpoint1" ]
push = [ "endpoint1" ]
```

It would reduce the noise within the configuration.

> Maybe we could start with a transport-internal mechanism, because that’s going to be much easier to design, and to move to a generic implementation in copy.Image only as other transports implement something similar and the requirements are better understood.

I agree to that, sounds good.

**Comment by mtrmac** [comment] 2019-01-18 18:04
> > @vrothberg WRT the Moby design, what does the array of `Push` endpoints actually mean?
> > 
> > * That each image _must_ be pushed to _all of them_?
> 
> Just to the first endpoint. Broadcasting might be considered in the future.

Then any of the endpoints but the first are _never_ used, are they? And having an array of push endpoints is not useful.

(Basically it seems to me that _none_ of the three semantics I suggested are useful — that mirror support in simple CLI clients can only only be useful on the read side.

When uploads can be aborted (in the worst case, by a machine losing power) at any time, coordinating uploads to multiple destinations would require a distributed locking mechanism with the ability to somehow restart/recover the upload, not something an one-shot c/image/docker client can do on its own (and docker/distribution does not have any distributed coordination mechanism anyway); it seems much more reasonable for the docker/distribution server to be responsible for coordinating uploads / distributing the uploaded image to mirrors, and only returning a “success” indication when it is committed to distributing the image successfully.])

**Comment by mtrmac** [comment] 2019-01-18 18:06
> Perfect. I looked at the code yesterday and wasn't sure if retries work _within_ dockerClient which drove me to the idea of moving the logic into `copy.Image ff`.

To be clear, the current implementation of c/image/docker, and `copy.Image`, _never_ retries anything in c/image/docker at all.

**Comment by mtrmac** [comment] 2019-01-18 18:20
> @vrothberg @mtrmac What do you think about the named endpoints and then referencing them? So for example this:
> 
> ```toml
> [endpoints]
> endpoint1 = "my-reg1.local"
> endpoint2 = "my-reg2.local"
> 
> [[registries]]
> prefix = "registry.local"
> pull = [ "endpoint1" ]
> push = [ "endpoint1" ]
> ```
> 
> It would reduce the noise within the configuration.

How would that actually work with mirrors?

Non-mirrored servers that are used directly can simply not configure any push/pull locations, and let the code default to the `Prefix` value.

If mirrors _are_ involved, it’s fairly likely that that would involve some kind of namespace mapping (e.g. mirroring `registry.access.redhat.com/rhel` to `mirror.example.com/redhat/rhel`). _Especially_ if a single local mirror server is used to mirror data from multiple different upstream registries, different namespaces on that single server pretty much _have_ to be used AFAICS.

And in that case, no two registries actually use the same pull/push prefixes for that mirror, even if they do share the hostname.  So, even if there were 20 entries in the registry configuration, with 20 different `Prefix` values, all referring to the same `mirror.example.com` host name, they would still need to use 20 different values for the “pull location” (`mirror.example.com/`{`redhat`,`ubuntu`,`docker`,`ISV1`,…}), and there would have to be 20 different definitions in the proposed `[endpoint]` section, each used exactly once.

---

I _would_, ideally, like to only have a single location for TLS configuration related to a host:port, so that disabling TLS or configuring expected CA certificates for `mirror.example.com` would only have to be done once and not 20 times; but that’s completely orthogonal to the mirror mechanism and “pull locations” (the TLS configuration does not conceptually care at all whether a registry is accessed directly or whether it is a mirror). See how 
https://github.com/containers/image/pull/468#discussion_r199617603 separates the two.

**Comment by vrothberg** [comment] 2019-01-20 12:39
> > Perfect. I looked at the code yesterday and wasn't sure if retries work _within_ dockerClient which drove me to the idea of moving the logic into `copy.Image ff`.
> 
> To be clear, the current implementation of c/image/docker, and `copy.Image`, _never_ retries anything in c/image/docker at all.

Right. I actually meant if retries "could" work and how it could be done.

**Comment by vrothberg** [comment] 2019-01-20 12:54
> My main starting point was the current structure and I experimented around with it to make it clearer to the end-user how it should be configured.
> 
> @vrothberg @mtrmac What do you think about the named endpoints and then referencing them? So for example this:
> 
> ```toml
> [endpoints]
> endpoint1 = "my-reg1.local"
> endpoint2 = "my-reg2.local"
> 
> [[registries]]
> prefix = "registry.local"
> pull = [ "endpoint1" ]
> push = [ "endpoint1" ]
> ```
> 
> It would reduce the noise within the configuration.

This may entirely be a matter of taste but I don't find it easier to comprehend nor less noisy. For now, I would only support pulling. If desired, we can add push semantics in the future (maybe with a `push=true` option or something while mirrors are ignored for pushs).

I suggest to move on and get the mirror semantics implemented in the docker client (see discussion above for details). @saschagrunert given you opened this issue, are you interested in contributing mirror-support for the docker client/transport?

**Comment by rhatdan** [comment] 2019-04-25 09:40
@saschagrunert @mtrmac @vrothberg Since the mirror patch was merged can we close this issue?

**Closed** 2019-04-25 09:44 UTC
