### ISSUE TITLE
Failed to disable shortname alias

### ISSUE THREAD

**Issue by QiWang19** [containers/image#1448] opened 2022-01-21 02:29 UTC
Crio has set `ShortNameModeDisabled` in PR https://github.com/cri-o/cri-o/pull/4983 to disable the shortname alias because this feature will break current users. But the alias are still be resolved from shipped alias config files on openshift 4.8.

containers/image should also disable the alias from alias config files when ShortNameModeDisabled is set. This issue was brought up by https://bugzilla.redhat.com/show_bug.cgi?id=2021026

With `ShortNameModeDisabled`, crio logs:
```
crio[1468]: time="2022-01-21 03:26:53.726515455Z" level=info msg="Pulling image: openshift3/oauth-proxy" file="server/image_pull.go:31" id=8cb48817-f9bf-4a03-ab5f-5c857b58ed98 name=/runtime.>
crio[1468]: time="2022-01-21 03:26:53.726628183Z" level=debug msg="Skipping non-existing decryption_keys_path: /etc/crio/keys/" file="server/utils.go:190"
crio[1468]: time="2022-01-21 03:26:53.726889563Z" level=info msg="Resolved \"openshift3/oauth-proxy\" as an alias (/etc/containers/registries.conf.d/001-rhel-shortnames.conf)" file="storage/>
crio[1468]: time="2022-01-21 03:26:53.767497636Z" level=debug msg="Request: &StatusRequest{Verbose:false,}" file="go-grpc-middleware/chain.go:25" id=04041da8-1e55-42d2-b375-a37c4534322d name>
crio[1468]: time="2022-01-21 03:26:53.767634258Z" level=debug msg="Response: &StatusResponse{Status:&RuntimeStatus{Conditions:[]*RuntimeCondition{&RuntimeCondition{Type:RuntimeReady,Status:t>
crio[1468]: time="2022-01-21 03:26:53.854240668Z" level=info msg="Trying to access \"registry.access.redhat.com/openshift3/oauth-proxy:latest\"" file="docker/docker_image_src.go:68"
```

**Comment by mtrmac** [comment] 2022-01-21 13:23
Thanks for your report.

That this mode does not affect aliases is intended behavior: Users can completely disable the insecure search behavior of `unqualified-search-registries`, while still having the convenience of aliases.

In fact, that’s the _preferred_ system setup, both secure and convenient.

If users don’t want aliases to be used, they shouldn’t configure them in the first place!

(Yes, I realize RHEL ships a set of aliases. If those are buggy or not desirable, that can’t be solved in this package.)

---

WRT https://bugzilla.redhat.com/show_bug.cgi?id=2021026 :
- Primary recommendation should be not to use short names in pod’s image specs. Use fully-qualified names, perhaps along with ICSP. That’s the _only_ fully supported approach.
- If I’m reading the bug right, they would be happy enough with a release note. Why not do just that?
- Alternatively, it might make sense to edit the shipped `aliases.conf` by the customer if they don’t like those names. (I don’t think we officially support adding ignition configs to edit files on nodes that way. Yes, I know, some customers do that anyway.)
- I could imagine that OpenShift’s CoreOS would want to edit or remove the `aliases.conf`, but it’s not very convincing — why would RHEL be shipping a configuration that is unsuitable for a RH product? Anyway the specific alias in question looks correct enough for RH users, if shipping aliases at all makes sense.
- It _is_ actually possible to opt out of the default aliases.conf in code, by pointing to a different configuration file. I feel fairly strongly that CRI-O shouldn’t be doing that, notably because such a code change would not affect Podman, and Podman is also used by OpenShift (at the very least during bootstrap). I guess it wouldn’t be my mess to maintain…

---

FWIW note that `ShortNameModeDisabled` is not “short names disabled”, it’s a confusing name for “short name secure setting disabled” — i.e. it’s the value that is _most_ liberal in interpreting short names. If anything, that would opt-in into using aliases, not prevent their use.

I’m rather baffled by https://github.com/cri-o/cri-o/pull/4983 ; it couldn’t have made any difference to any behavior AFAICT. (And indeed, https://bugzilla.redhat.com/show_bug.cgi?id=2021026 points to introduction of the `shortnames` use, not to the commit chaining the short name mode.)

(Pesky reminder: Using K8s and passing credentials via CRI was always broken if `unqualified-search-registries` is not set to exactly `docker.io`; so OpenShift should not be allowing to set `unqualified-search-registries` to anything else. Yeah, customers want that, and they should have been told no. At the very least recommend against its use.)

**Comment by vrothberg** [comment] 2022-01-21 13:36
Wonderful summary, @mtrmac.  I have nothing to add other than the behavior is documented (see https://github.com/containers/image/blob/main/docs/containers-registries.conf.5.md#short-name-aliasing-modes):

> When pulling a short name, the configured aliases table will be used for resolving the short name. If a matching alias is found, it will be used without further consulting the unqualified-search registries list. If no matching alias is found, the behavior can be controlled via the short-name-mode option as described below.
[...]
> disabled: Use all unqualified-search registries without prompting.

**Comment by vrothberg** [comment] 2022-01-21 13:36
But in theory, a knob in `types.SystemContext` to skip aliases is doable.

**Comment by mtrmac** [comment] 2022-01-21 13:49
It basically already exists. I don’t think it’s a good idea to use it, but after losing the USR fight in OpenShift, I’m not going to fight over this one any more forcefully. OpenShift users just might get all the pain they opted in to.

**Comment by umohnani8** [comment] 2022-01-21 14:43
So iiuc, the issue here is not that it is resolving the short name to an alias found in the alias files, but it is resolving to check all the registries under the `unqualified-search-registries` list? Setting it to `disable` is the original behaviour we had of checking the `unqualified-search-registries` list when a short name image is used, right?

**Comment by mtrmac** [comment] 2022-01-21 15:08
AFAICT the _situation_ in https://bugzilla.redhat.com/show_bug.cgi?id=2021026 is that the user has a disconnected system, and does that by using unqualified names and changing USR, not by using ICSP.

That breaks because one of the unqualified images in on the default alias list (well, in addition to all the other ways using USR breaks).

It doesn’t get to search the USR list, which the customer expects it to do.

Setting `short-name-mode` to anything doesn’t change that situation, and isn’t supposed to.

---

The situation in https://bugzilla.redhat.com/show_bug.cgi?id=1969599 seems to be that the user is using unqualified names, and that broke something (our defaults??) were shipping a nonsensical alias value.

The issue here is obviously the nonsensical alias value, and I can’t find any record of why that wasn’t the thing that was changed.

**Comment by mtrmac** [comment] 2022-01-21 15:18
> It doesn’t get to search the USR list, which the customer expects it to do.

BTW they can still use the USR-based design along with the default aliases, by adding an ICSP configuration pointing the alias destination to their mirror. That’s one more Rube Goldberg element but it allows them to continue using the (fundamentally broken) unqualified names.

**Comment by mtrmac** [comment] 2022-12-09 03:24
Yes, let’s close this. The configuration is interpreted consistently with the design and documentation.

**Closed by mtrmac** 2022-12-09 03:24 UTC
