### ISSUE TITLE
Avoid usage of github.com/mtrmac/gpgme

### ISSUE THREAD

**Issue by hferentschik** [containers/image#268] opened 2017-05-10 18:27 UTC
This library only compiles on Linux, since it uses C extensions which won't compile on OS X and Windows. This makes it for example hard/impossible to use _image_ as a library for a cross compiled CLI applications. 

Could one not use Go's golang.org/x/crypto/openpgp?

For now I removed _github.com/mtrmac/gpgme_ and commented its use out from _mechanism.go_. If there is no way to make without C extensions, one can maybe only build them for Linux, whereas for OS X and Windows it particular feature would not be available (not 100% for what it is actually used).

**Comment by runcom** [comment] 2017-05-10 18:34
you can use build tag `containers_image_openpgp` to not use `gpgme` but getting only a limited signing features, @mtrmac could you chime in here?

**Comment by hferentschik** [comment] 2017-05-10 18:49
Yes, I've seen

> Optionally, you can use the containers_image_openpgp build tag (using go build -tags …, or make … BUILDTAGS=…). This will use a Golang-only OpenPGP implementation for signature verification instead of the default cgo/gpgme-based implementation; 

I have not got this to work yet though. Also from a user point of view it would be nice, if the default would work for all OS types.

That said, there is another problem with:

    vendor/github.com/containers/storage/storage/lockfile.go:136: st.Mtim undefined (type syscall.Stat_t has no field or method Mtim)

The call to _syscall.Stat_t_ is OS specific and returns different structs depending on the target OS. I guess that's an issue for _storage_.

**Comment by hferentschik** [comment] 2017-05-11 09:30
_containers_image_openpgp_ tag aside, I still cannot compile this out of the box. _mtrmac/gpgme_ is a defined dependency which gets downloaded into the vendor directory. When I then try to build, I get:

    # github.com/containers/image/vendor/github.com/mtrmac/gpgme
    vendor/github.com/mtrmac/gpgme/data.go:4:11: fatal error: 'gpgme.h' file not found
    #include <gpgme.h>
              ^
    1 error generated.

    # github.com/containers/image/vendor/github.com/containers/storage/storage
    vendor/github.com/containers/storage/storage/lockfile.go:136: st.Mtim undefined (type syscall.Stat_t has no field or method Mtim)
    vendor/github.com/containers/storage/storage/lockfile.go:136: not enough arguments in call to time.Unix

So even if containers/image has some build tags to avoid the usage of gpgme, gpgme will cause compilation errors. 

The second error is the mentioned system specific call to syscall.Stat_t in containers/storage.

**Comment by mtrmac** [comment] 2017-05-11 10:21
> Also from a user point of view it would be nice, if the default would work for all OS types.

The `openpgp` backend is limited (verification only, no signing), so there are two dimensions of “work” which may be in conflict.

Though, AFAICT, the situation for macOS and Linux is pretty much the same: GPGME development libraries have to be installed. In neither it is a part of the mandatory base system, so it may need to be installed by the user. I suppose with Linux it may be a little easier when using a container to isolate a prepared build environment, but then a container runtime is not a part of the mandatory base system either…

**Comment by mtrmac** [comment] 2017-05-11 10:24
> _containers_image_openpgp_ tag aside, I still cannot compile this out of the box. _mtrmac/gpgme_ is a defined dependency which gets downloaded into the vendor directory. When I then try to build, I get:
> 
>     # github.com/containers/image/vendor/github.com/mtrmac/gpgme
>     vendor/github.com/mtrmac/gpgme/data.go:4:11: fatal error: 'gpgme.h' file not found
>     #include <gpgme.h>
>               ^
>     1 error generated.

What _exact_ command are you using to build this? This should only happen when the build tag is not present. (Alternatively, install a GPGME development library + headers, via `brew` or whatever cgo can find.)

>     # github.com/containers/image/vendor/github.com/containers/storage/storage
>     vendor/github.com/containers/storage/storage/lockfile.go:136: st.Mtim undefined (type syscall.Stat_t has no field or method Mtim)
>     vendor/github.com/containers/storage/storage/lockfile.go:136: not enough arguments in call to time.Unix

This is the same thing as https://github.com/projectatomic/skopeo/issues/310 , where the supposed fix https://github.com/projectatomic/skopeo/pull/331 lacks a macOS tester. Could you verify that PR works, please? If it does, we can update the vendored version in this repo similarly.

**Comment by hferentschik** [comment] 2017-05-12 05:15
> What exact command are you using to build this? This should only happen when the build tag is not present

Let me double check

> This is the same thing as projectatomic/skopeo#310 , where the supposed fix projectatomic/skopeo#331 lacks a macOS tester. Could you verify that PR works, please?

Will do.

**Comment by hferentschik** [comment] 2017-05-12 12:54
So there is the thing. If I do:

    $ make vendor
    $ go build -tags="containers_image_openpgp" ./...
    # github.com/containers/image/vendor/github.com/containers/storage/storage
    vendor/github.com/containers/storage/storage/lockfile.go:136: st.Mtim undefined (type     syscall.Stat_t has no field or method Mtim)
    vendor/github.com/containers/storage/storage/lockfile.go:136: not enough arguments in call to time.Unix
    # github.com/containers/image/vendor/github.com/mtrmac/
    vendor/github.com/mtrmac/gpgme/data.go:4:11: fatal error: 'gpgme.h' file not found
    #include <gpgme.h>
          ^
    1 error generated.

If I then manually delete the mtrmac:

    $ rm -rf vendor/github.com/mtrmac/gpgme
    $ go build -tags="containers_image_openpgp" ./...
    # github.com/containers/image/vendor/github.com/containers/storage/storage
    vendor/github.com/containers/storage/storage/lockfile.go:136: st.Mtim undefined (type syscall.Stat_t has no field or method Mtim)
    vendor/github.com/containers/storage/storage/lockfile.go:136: not enough arguments in call to time.Unix

storage issue aside, if I don't want to use gpgme, I not only have to specify the _containers_image_openpgp_ tag, but I also need to make sure not to get the gpgme dependency. Using _make vendor_ I will get it per default though. So at the very least this needs to be documented. 

In the REAMDE it says regarding _gpgme_:

> the primary downside is that creating new signatures with the Golang-only implementation is not supported.

So where is that really an issue. What is the use case for creating signatures?

**Comment by hferentschik** [comment] 2017-05-12 13:10
Updating to the latest version of storage by adding:

    github.com/containers/storage d10d8680af74070b362637408a7fe28c4b1f1eff
    github.com/tchap/go-patricia/patricia v2.2.6
    github.com/opencontainers/selinux ba1aefe8057f1d0cfb8e88d0ec1dc85925ef987d

to vendor.conf, gets me past compilation errors.

**Comment by mtrmac** [comment] 2017-05-12 14:17
> If I then manually delete the mtrmac:

Good catch, `./...` includes all of the `vendor` subdirectory. That documentation needs to be fixed.

Also thanks for testing the storage update. I’ll work on on the necessary updates.

> What is the use case for creating signatures?

Well, a signature has to exist in order to be verifiable :)  If you mean that your intended use of containers/image does not involve signing container images, sure, that’s not inherently required. Much of the library does not actually require the `containers/image/signature` subpackage and can be used completely independently (but the full `copy.Image` pipeline does depend on the signature subpackage).

**Comment by rhatdan** [comment] 2019-04-25 09:28
@hferentschik @mtrmac @vrothberg I believe this is fixed, Closing. Reopen if I am mistaken.

**Closed by rhatdan** 2019-04-25 09:28 UTC

**Comment by mtrmac** [comment] 2019-05-07 17:32
Yes, this was fixed by #271 and #272.

**Comment by wlei27** [comment] 2021-06-03 14:53
@markmc Can you tell the cause that the signing is not supported by openpgp ? 
The openpgp supports the verification. If the image is signed using the gpgme,  would the image be verified using the openpgp ? Thanks!
