### ISSUE TITLE
`trash` fails to build the cache

### ISSUE THREAD

**Issue by nlewo** [containers/image#372] opened 2017-11-02 17:09 UTC
make test
INFO[0000] Trash! Reading file: 'vendor.conf'           
INFO[0000] Preparing cache for 'github.com/BurntSushi/toml' 
INFO[0002] Checking out 'github.com/BurntSushi/toml', commit: 'b26d9c308763d68093482582cea63d69be07a0f0' 
INFO[0002] Preparing cache for 'github.com/containers/storage' 
INFO[0028] Checking out 'github.com/containers/storage', commit: '47536c89fcc545a87745e1a1573addc439409165' 
INFO[0028] Preparing cache for 'github.com/davecgh/go-spew' 
INFO[0030] Checking out 'github.com/davecgh/go-spew', commit: '346938d642f2ec3594ed81d874461961cd0faa76' 
INFO[0030] Preparing cache for 'github.com/docker/distribution' 
INFO[0039] Checking out 'github.com/docker/distribution', commit: '5f6282db7d65e6d72ad7c2cc66310724a57be716' 
INFO[0039] Preparing cache for 'github.com/docker/docker' 
INFO[0090] Checking out 'github.com/docker/docker', commit: '30eb4d8cdc422b023d5f11f29a82ecb73554183b' 
INFO[0091] Preparing cache for 'github.com/docker/docker-credential-helpers' 
INFO[0092] Checking out 'github.com/docker/docker-credential-helpers', commit: 'd68f9aeca33f5fd3f08eeae5e9d175edf4e731d1' 
INFO[0092] Preparing cache for 'github.com/docker/go-connections' 
INFO[0095] Checking out 'github.com/docker/go-connections', commit: '3ede32e2033de7505e6500d6c868c2b9ed9f169d' 
INFO[0095] Preparing cache for 'github.com/docker/go-units' 
INFO[0096] Checking out 'github.com/docker/go-units', commit: '0dadbb0345b35ec7ef35e228dabb8de89a65bf52' 
INFO[0096] Preparing cache for 'github.com/docker/libtrust' 
INFO[0097] Checking out 'github.com/docker/libtrust', commit: 'aabc10ec26b754e797f9028f4589c5b7bd90dc20' 
INFO[0097] Preparing cache for 'github.com/ghodss/yaml' 
INFO[0099] Checking out 'github.com/ghodss/yaml', commit: '04f313413ffd65ce25f2541bfd2b2ceec5c0908c' 
INFO[0099] Preparing cache for 'github.com/gogo/protobuf/proto' 
INFO[0100] Checking out 'github.com/gogo/protobuf/proto', commit: 'fcdc5011193ff531a548e9b0301828d5a5b97fd8' 
INFO[0100] Fetching latest commits from 'origin' for 'github.com/gogo/protobuf/proto' 
ERRO[0100] `git fetch -f -t origin` failed:
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
 
FATA[0100] fetch failed                                  i={Package:github.com/gogo/protobuf/proto Version:fcdc5011193ff531a548e9b0301828d5a5b97fd8 Repo: Options:{Transitive:false Staging:false}}
make: *** [Makefile:40: vendor] Error 1

**Comment by mtrmac** [comment] 2017-11-04 20:09
Thanks for the report.

With `go version go1.8.3 darwin/amd64` and `trash version v0.3.0-dev` (commit afed821794b6182227a1834300ee6e02f296895c ) , this works as expected for me.

Skopeo’s `vendor` tool also can process the `github.com/gogo/protobuf/proto` subpackage specifier correctly.

I suppose the fix in #373 can’t hurt either way, but it would still be interesting to understand the root cause of the breakage.

**Comment by mtrmac** [comment] 2018-01-29 15:13
The equivalent of #373 has been merged in #305, so hopefully this now works. Please reopen if that’s not the case.

**Closed by mtrmac** 2018-01-29 15:13 UTC
